// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWPdm.Sample.Data;

#nullable disable

namespace SWPdm.Sample.Data.Migrations
{
    [DbContext(typeof(PdmDbContext))]
    partial class PdmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmBomOccurrence", b =>
                {
                    b.Property<long>("BomOccurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("bom_occurrence_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BomOccurrenceId"));

                    b.Property<string>("ChildConfigurationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("child_configuration_name");

                    b.Property<long?>("ChildVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("child_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FindNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("find_number");

                    b.Property<bool>("IsSuppressed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_suppressed");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_virtual");

                    b.Property<string>("OccurrencePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("occurrence_path");

                    b.Property<string>("PackageRelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package_relative_path");

                    b.Property<string>("ParentConfigurationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parent_configuration_name");

                    b.Property<long>("ParentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_version_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReferenceStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reference_status");

                    b.Property<string>("SourceReferencePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_reference_path");

                    b.HasKey("BomOccurrenceId");

                    b.HasIndex("ChildVersionId")
                        .HasDatabaseName("idx_pdm_bom_occurrences_child");

                    b.HasIndex("ParentVersionId")
                        .HasDatabaseName("idx_pdm_bom_occurrences_parent");

                    b.HasIndex("ParentVersionId", "OccurrencePath")
                        .IsUnique()
                        .HasDatabaseName("uq_pdm_bom_occurrences_parent_path");

                    b.HasIndex("ReferenceStatus", "IsSuppressed")
                        .HasDatabaseName("idx_pdm_bom_occurrences_status");

                    b.ToTable("pdm_bom_occurrences", null, t =>
                        {
                            t.HasCheckConstraint("ck_pdm_bom_occurrences_status", "reference_status IN ('Resolved', 'Broken', 'Virtual', 'Missing')");
                        });
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmCustomProperty", b =>
                {
                    b.Property<long>("CustomPropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("custom_property_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomPropertyId"));

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("configuration_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("property_name");

                    b.Property<string>("PropertyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("property_type");

                    b.Property<string>("PropertyValue")
                        .HasColumnType("text")
                        .HasColumnName("property_value");

                    b.Property<string>("RawExpression")
                        .HasColumnType("text")
                        .HasColumnName("raw_expression");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    b.HasKey("CustomPropertyId");

                    b.HasIndex("PropertyName", "PropertyValue")
                        .HasDatabaseName("idx_pdm_custom_properties_lookup");

                    b.HasIndex("VersionId", "ConfigurationName", "PropertyName")
                        .IsUnique()
                        .HasDatabaseName("uq_pdm_custom_properties");

                    b.ToTable("pdm_custom_properties", (string)null);
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CurrentVersionId")
                        .HasColumnType("bigint")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Designer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("designer");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_type");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("file_extension");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_number");

                    b.Property<string>("RevisionLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision_label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("DocumentId");

                    b.HasIndex("CurrentVersionId");

                    b.ToTable("pdm_documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_pdm_documents_extension", "file_extension IN ('.sldprt', '.sldasm', '.slddrw')");

                            t.HasCheckConstraint("ck_pdm_documents_type", "document_type IN ('Part', 'Assembly', 'Drawing')");
                        });
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocumentVersion", b =>
                {
                    b.Property<long>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VersionId"));

                    b.Property<string>("ChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<DateTimeOffset?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<string>("RevisionLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("revision_label");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_file_path");

                    b.Property<DateTimeOffset?>("SourceLastWriteUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_last_write_utc");

                    b.Property<string>("StorageFileId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("storage_file_id");

                    b.Property<string>("VaultRelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vault_relative_path");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("VersionId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_pdm_document_versions_document_id");

                    b.HasIndex("StorageFileId")
                        .IsUnique()
                        .HasDatabaseName("uq_pdm_document_versions_storage_file_id");

                    b.HasIndex("DocumentId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("uq_pdm_document_versions_doc_ver");

                    b.ToTable("pdm_document_versions", (string)null);
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmBomOccurrence", b =>
                {
                    b.HasOne("SWPdm.Sample.Data.Entities.PdmDocumentVersion", "ChildVersion")
                        .WithMany("ChildBomOccurrences")
                        .HasForeignKey("ChildVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SWPdm.Sample.Data.Entities.PdmDocumentVersion", "ParentVersion")
                        .WithMany("ParentBomOccurrences")
                        .HasForeignKey("ParentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildVersion");

                    b.Navigation("ParentVersion");
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmCustomProperty", b =>
                {
                    b.HasOne("SWPdm.Sample.Data.Entities.PdmDocumentVersion", "Version")
                        .WithMany("CustomProperties")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocument", b =>
                {
                    b.HasOne("SWPdm.Sample.Data.Entities.PdmDocumentVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocumentVersion", b =>
                {
                    b.HasOne("SWPdm.Sample.Data.Entities.PdmDocument", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SWPdm.Sample.Data.Entities.PdmDocumentVersion", b =>
                {
                    b.Navigation("ChildBomOccurrences");

                    b.Navigation("CustomProperties");

                    b.Navigation("ParentBomOccurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
