CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE TABLE pdm_bom_occurrences (
        bom_occurrence_id bigint GENERATED BY DEFAULT AS IDENTITY,
        parent_version_id bigint NOT NULL,
        child_version_id bigint,
        occurrence_path character varying(1000) NOT NULL,
        parent_configuration_name character varying(255) NOT NULL,
        child_configuration_name character varying(255) NOT NULL,
        quantity numeric(18,6) NOT NULL,
        find_number character varying(50),
        source_reference_path text NOT NULL,
        package_relative_path text NOT NULL,
        reference_status character varying(20) NOT NULL,
        is_suppressed boolean NOT NULL,
        is_virtual boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pdm_bom_occurrences" PRIMARY KEY (bom_occurrence_id),
        CONSTRAINT ck_pdm_bom_occurrences_status CHECK (reference_status IN ('Resolved', 'Broken', 'Virtual', 'Missing'))
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE TABLE pdm_custom_properties (
        custom_property_id bigint GENERATED BY DEFAULT AS IDENTITY,
        version_id bigint NOT NULL,
        configuration_name character varying(255) NOT NULL,
        property_name character varying(128) NOT NULL,
        property_value text,
        property_type character varying(50),
        raw_expression text,
        is_resolved boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pdm_custom_properties" PRIMARY KEY (custom_property_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE TABLE pdm_document_versions (
        version_id bigint GENERATED BY DEFAULT AS IDENTITY,
        document_id bigint NOT NULL,
        version_no integer NOT NULL,
        revision_label character varying(50),
        google_drive_file_id character varying(255) NOT NULL,
        original_file_name character varying(255) NOT NULL,
        source_file_path text NOT NULL,
        vault_relative_path text NOT NULL,
        checksum_sha256 character varying(64),
        file_size_bytes bigint,
        source_last_write_utc timestamp with time zone,
        parsed_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pdm_document_versions" PRIMARY KEY (version_id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE TABLE pdm_documents (
        document_id bigint GENERATED BY DEFAULT AS IDENTITY,
        file_name character varying(255) NOT NULL,
        file_extension character varying(10) NOT NULL,
        document_type character varying(20) NOT NULL,
        part_number character varying(100),
        revision_label character varying(50),
        material character varying(100),
        designer character varying(100),
        current_version_id bigint,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_pdm_documents" PRIMARY KEY (document_id),
        CONSTRAINT ck_pdm_documents_extension CHECK (file_extension IN ('.sldprt', '.sldasm', '.slddrw')),
        CONSTRAINT ck_pdm_documents_type CHECK (document_type IN ('Part', 'Assembly', 'Drawing')),
        CONSTRAINT "FK_pdm_documents_pdm_document_versions_current_version_id" FOREIGN KEY (current_version_id) REFERENCES pdm_document_versions (version_id) ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX idx_pdm_bom_occurrences_child ON pdm_bom_occurrences (child_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX idx_pdm_bom_occurrences_parent ON pdm_bom_occurrences (parent_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX idx_pdm_bom_occurrences_status ON pdm_bom_occurrences (reference_status, is_suppressed);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_pdm_bom_occurrences_parent_path ON pdm_bom_occurrences (parent_version_id, occurrence_path);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX idx_pdm_custom_properties_lookup ON pdm_custom_properties (property_name, property_value);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_pdm_custom_properties ON pdm_custom_properties (version_id, configuration_name, property_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX idx_pdm_document_versions_document_id ON pdm_document_versions (document_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_pdm_document_versions_doc_ver ON pdm_document_versions (document_id, version_no);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_pdm_document_versions_drive_file_id ON pdm_document_versions (google_drive_file_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    CREATE INDEX "IX_pdm_documents_current_version_id" ON pdm_documents (current_version_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    ALTER TABLE pdm_bom_occurrences ADD CONSTRAINT "FK_pdm_bom_occurrences_pdm_document_versions_child_version_id" FOREIGN KEY (child_version_id) REFERENCES pdm_document_versions (version_id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    ALTER TABLE pdm_bom_occurrences ADD CONSTRAINT "FK_pdm_bom_occurrences_pdm_document_versions_parent_version_id" FOREIGN KEY (parent_version_id) REFERENCES pdm_document_versions (version_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    ALTER TABLE pdm_custom_properties ADD CONSTRAINT "FK_pdm_custom_properties_pdm_document_versions_version_id" FOREIGN KEY (version_id) REFERENCES pdm_document_versions (version_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    ALTER TABLE pdm_document_versions ADD CONSTRAINT "FK_pdm_document_versions_pdm_documents_document_id" FOREIGN KEY (document_id) REFERENCES pdm_documents (document_id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415104839_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415104839_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

